### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by dallenwilson** [dallenwilson/SGCraft#1]
Tracking planned changes here, to keep it out of the vcs. Feel free to comment with arguments for/against or to add ideas. Some of this is probably suitable for merging upstream. Issue will be edited as things change.

- [] Clean-up temple generation code
- [] Re-vamp Temple generation
    - [] Desert Temple: Spawn gate in main chamber, not underneath
    - [] Jungle Temple: Spawn gate on top of temple, not outside buried in the jungle
    - [] Igloo: Spawn gate underneath igloo in chamber, not outside.
    - [] Swamp: Place gate on stone platform rather than dirt/grass. Add chance to spawn only above ground instead of half-buried or submerged as it usually seems to.
- [] Add gate generation to rambling-structures (1-per if possible)
    - [] Villages
    - [] Nether Fortress
    - [] Stronghold
    - [] Woodland Mansion
    - [] End City
- [] Move chevronUpgrade from gate to DHD
    - This matches canon, as all Milky Way / Pegasus gates are capable of dialing 8+ symbol locations, if the control system (DHD, SGC Computer, etc) and energy supply supports it.
- [] Add upgrade recipes for computer interface blocks, allowing chevronUpgrade dialing (core crystal in recipe) and fast/no-spin dialing (control crystal in recipe)
- [] Remove IC2/RF power blocks, integrate functionality directly in the gate base block
    - This matches canon. Multiple examples of a Milky Way gate being powered directly (wire-wrapped and lightning zapped, conductive-vine and plant-based cold fusion, etc) and then dialed manually once the inner ring unlocks.
- [] Add canManualDial option, true for Milky Way gate, false for others
    - Add Gui, 3 buttons and symbol display. If gate energy buffer is full, inner ring is unlocked and can be rotated by button one symbol at a time, with third button to lock chevron.
    - One-second delay on ring-rotation button presses, to keep it nice and tedious. Allow rotation either direction after every lock, because we're not completely heartless.
- [] Add Tollan gate (no manual dial, no spin-dial. DHD or upgraded computer interface only)
    - [] Generate .smeg models
    -OR-
    - [] Transition to more 'standard' modeling, starting with Tollan gate

**Comment by Dockter** [comment]
I would love to get away from the .smeg format.  I have no way of re-creating them.  I've tried several times with Sketchit 7 and Greg's exporter he posted.

**Comment by dallenwilson** [comment]
I made a half-hearted attempt to get Sketchup 7 and Sketchup 8 running with the python plugin but didn't get very far. Having to work with them through VMWare and a Win7 virtual machine was enough extra frustration that I didn't try very hard when things started not-working.

Have you considered collaborating with [AUNIS](https://github.com/MrJake222/AUNIS)? MrJake222 has some beautiful models in that mod.
